#!/bin/bash
#
# Description: Configures systemd services to my liking.
#
# Many of these tweaks are from https://eklitzke.org/lobotomizing-gnome
#
# Homepage: https://gitlab.com/krathalan
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# ------------------
# --- Guidelines ---
# ------------------

# This script follows the Google Shell Style Guide: 
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# --------------------------------------
# --------------- Script ---------------
# --------------------------------------

echo -e "This script should be run NOT AS ROOT (or sudo)!"
read -r -p "Press enter when you are ready to continue, or <CTRL+C> to exit: "

# Security concerns
systemctl disable telnet.service
systemctl stop telnet.service

# Fully disable Bluetooth
systemctl disable bluetooth.service
systemctl stop bluetooth.service
systemctl --user disable obex.service
systemctl --user stop obex.service

# Disable Gnome Virtual Online Accounts Monitor
systemctl --user disable gvfs-goa-volume-monitor.service
systemctl --user mask gvfs-goa-volume-monitor.service
systemctl --user stop gvfs-goa-volume-monitor.service

# Disable GNOME Tracker
systemctl --user disable tracker-store.service
systemctl --user mask tracker-store.service
systemctl --user stop tracker-store.service

# Disable GNOME Evolution services (I use Thunderbird!)
systemctl --user disable evolution-addressbook-factory.service
systemctl --user mask evolution-addressbook-factory.service 
systemctl --user stop evolution-addressbook-factory.service
systemctl --user disable evolution-calendar-factory.service
systemctl --user mask evolution-calendar-factory.service
systemctl --user stop evolution-calendar-factory.service
systemctl --user disable evolution-source-registry.service
systemctl --user mask evolution-source-registry.service
systemctl --user stop evolution-source-registry.service