#!/bin/bash
# From an anonymous gist on Github
# https://gist.github.com/anonymous/a588e2ca9160d5fb142b
# https://web.archive.org/web/20190511164651/https://gist.github.com/anonymous/a588e2ca9160d5fb142b

set -e

ALL=$(pacman --query --quiet --explicit)
BASE=$(pacman --query --quiet --groups  base)
BASE_DEVEL=$(pacman --query --quiet --groups base-devel)

echo "$ALL
$BASE
$BASE
$BASE_DEVEL
$BASE_DEVEL" | sort | uniq -u
