#!/usr/bin/env bash
#
# Description: Script for calculating Mythic+ Event ratings.
#
# Homepage: https://git.sr.ht/~krathalan/miscellaneous-scripts
#
# Copyright (C) 2020 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# EXPECTED INPUT -- example file:
# $ cat example_input
# Ahkenatan chogall
# Morisong chogall
# Tireiron laughing-skull
# Euphoric chogall

# -----------------------------------------
# -------------- Guidelines ---------------
# -----------------------------------------

# This script follows the Google Shell Style Guide:
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# -----------------------------------------
# ----------- Program variables -----------
# -----------------------------------------

# Colors
readonly RED=$(tput bold && tput setaf 1)
readonly NC=$(tput sgr0) # No color/turn off all tput attributes

# Other
readonly SCRIPT_NAME=$(basename "$0")
readonly INPUT_FILE="${1:-}"
readonly OUTPUT_FILE="ratings.txt"

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

#######################################
# Returns rating information for a given character.
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: realm/server, e.g. chogall
#   $2: character name, e.g. Ahkenatan
# Returns:
#   rating
#######################################
resolve_character_score()
{
  local -r raiderIOJson="$(wget -qO- --header "Accept: application/json" "https://raider.io/api/v1/characters/profile?region=us&realm=$1&name=$2&fields=gear%2Cmythic_plus_scores_by_season%3Acurrent%2Cmythic_plus_best_runs")"

  mapfile -t parsedJson <<< "$(jq -r ".active_spec_role, .mythic_plus_scores_by_season[0].scores.all, .mythic_plus_best_runs[0].mythic_level, .gear.item_level_equipped, .class" <<< "${raiderIOJson}")"

  # 0: active spec role
  # 1: raider.io overall score
  # 2: highest key score
  # 3: equipped ilvl
  # 4: class

  # printf "%.0f" is used to round the number
  local -r rating=$(printf "%.0f" "$(bc <<< "(${parsedJson[3]} / 10 * ${parsedJson[2]}) + ${parsedJson[1]}")")

  printf "%s -- %s, %s %s %s\n" "${rating}" "$2" "${parsedJson[3]}" "${parsedJson[0]}" "${parsedJson[4]}" >> "${OUTPUT_FILE}"
}

#######################################
# Prints passed error message before premature exit.
# Prints everything to >&2 (STDERR).
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: error message to print
# Returns:
#   none
#######################################
exit_script_on_failure()
{
  printf "%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
  printf "Exiting %s Bash script.\n" "${SCRIPT_NAME}" >&2

  exit 1
}

# -----------------------------------------
# ---------------- Script -----------------
# -----------------------------------------

if [[ "$(whoami)" = "root" ]]; then
  exit_script_on_failure "This script should NOT be run as root (or sudo)!"
fi

rm -f "${OUTPUT_FILE}"

if [[ ! -f "${INPUT_FILE}" ]]; then
  exit_script_on_failure "Please specify a file with a list of character names."
fi

mapfile -t characters < "${INPUT_FILE}"

for char in "${characters[@]}"; do
  resolve_character_score "${char##* }" "${char%% *}" &
done

wait

# Sort output from highest rating to lowest
sort -r -n -o "${OUTPUT_FILE}" "${OUTPUT_FILE}"

# Add header
sed -i "1s#^#======================================================\n|      Collector's Anonymous Mythic Plus Ratings     |\n|              Generated on $(date "+%b %d, %Y")             |\n| https://git.sr.ht/~krathalan/miscellaneous-scripts |\n======================================================\n\nRating -- Character, ilvl role class\n=====================================\n#" "${OUTPUT_FILE}"
