#!/bin/sh
#
# Description: Sets up Arch Linux with the software I use, and 
#              configures various aspects of each system to my liking.
#
# Homepage: https://gitlab.com/krathalan/miscellaneous-scripts
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -----------------------------------------
# -------------- Guidelines ---------------
# -----------------------------------------

# This script follows the Google Shell Style Guide: 
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eu # (Eo pipefail) is bash only!

# -----------------------------------------
# ----------- Program variables -----------
# -----------------------------------------

# Colors
readonly GREEN=$(tput bold && tput setaf 2)
readonly RED=$(tput bold && tput setaf 1)
readonly PURPLE=$(tput bold && tput setaf 5)
readonly NC=$(tput sgr0) # No color/turn off all tput attributes

# Step variables
stepCounter=1
stepWithColor="${PURPLE}${stepCounter}${NC}"

# Other
readonly SCRIPT_NAME=$(basename "$0")

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

#######################################
# Prints passed error message before premature exit.
# Prints everything to >&2 (STDERR).
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: error message to print
# Returns:
#   none
#######################################
exit_script_on_failure() 
{
  printf "\n[%s✖%s] Error: %s\n" "${RED}" "${NC}" "$1" >&2
  printf "Exiting %s Bash script.\n" "${SCRIPT_NAME}" >&2

  exit 1
}

#######################################
# Prints "Done."
# Globals:
#   PURPLE, stepCounter, NC
# Arguments:
#   none
# Returns:
#   none
#######################################
print_done() 
{
  stepCounter=$(( stepCounter + 1 ))
  stepWithColor="${PURPLE}${stepCounter}${NC}"
  printf "Done.\n\n"
}

# -----------------------------------------
# ---------------- Script -----------------
# -----------------------------------------

# Print intro
printf "Starting %s Bash script; Copyright (C) 2019-%s krathalan\n" "${SCRIPT_NAME}" "$(date +%Y)"
printf "This is free software: you are free to change and redistribute it.\n"
printf "There is NO WARRANTY, to the extent permitted by law.\n\n"

if [ "$(whoami)" = "root" ]; then
  exit_script_on_failure "This script should NOT be run as root (or sudo)!"
fi

printf "%s. Installing fonts with pacman...\n" "${stepWithColor}"
sudo pacman -S --needed noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-dejavu ttf-linux-libertine ttf-roboto 
print_done

printf "%s. Installing packages with pacman...\n" "${stepWithColor}"
# Kernel packages
sudo pacman -S --needed linux-lts

# System packages
sudo pacman -S --needed alacritty alacritty-terminfo alsa-plugins apparmor bash-completion bluez-utils cups cups-pdf dash dictd ffmpeg gptfdisk gst-libav hplip iftop intel-ucode iw iwd ncdu notification-daemon ntfs-3g pamixer pavucontrol pigz playerctl pulseaudio-alsa source-highlight system-config-printer tmux tree unzip wget wireguard-arch wireguard-lts wireguard-tools zip

# Development packages
sudo pacman -S --needed clang geany geany-plugins lld llvm meson ninja shellcheck valgrind

# User packages
sudo pacman -S --needed android-tools bookworm borg eog evince firefox gimp git gnome-calculator gnome-characters imagemagick irssi jq mediainfo libreoffice-fresh lollypop mosh mpv neofetch papirus-icon-theme pass perl-image-exiftool reflector streamlink stress syncthing thunderbird transmission-cli youtube-dl zim

# Needed for some features/to play some codecs
sudo pacman -S --needed gst-plugins-base gst-plugins-good

# Dependency for building yay
sudo pacman -S --needed --asexplicit go

# Dependency for building pulseaudio-modules-bt-git
sudo pacman -S --needed cmake
print_done

if [ -x "$(command -v "yay")" ]; then
  printf "%s. Installing packages from AUR...\n" "${stepWithColor}"
  yay -S firefox-nightly hardened-malloc-git libldac nano-syntax-highlighting-git plata-theme sparse ttf-material-design-icons-webfont ttf-roboto-mono wtwitch yay
  yay -S pulseaudio-modules-bt-git
  print_done
fi

# From https://bbs.archlinux.org/viewtopic.php?id=173653
printf "%s. Adding .gif thumbnailer for file browsers...\n" "${stepWithColor}"
sudo pacman -S --needed ffmpegthumbnailer

if ! grep -q -i "MimeType=image/gif" /usr/share/thumbnailers/ffmpegthumbnailer.thumbnailer; then
  sudo sed -i "s#MimeType=#MimeType=image/gif;#" /usr/share/thumbnailers/ffmpegthumbnailer.thumbnailer
fi

rm -rf "${HOME}/.cache/thumbnails"
print_done

printf "%s Performing machine-specific configuration...\n" "${stepWithColor}"

# Machine specific configuration
if grep -q desktop /etc/hostname; then
  # Hi-DPI scaling
  echo "GDK_SCALE=2" | sudo tee -a /etc/environment > /dev/null

  # Fix tiling background
  sudo pacman -S --needed feh

  # X11 packages
  sudo pacman -S --needed compton dmenu dunst i3-gaps i3lock i3status redshift scrot
  
  printf "%s Installing gaming software...\n" "${stepWithColor}"

  if ! grep -q "#\[multilib\]" /etc/pacman.conf; then
    # NVIDIA drivers
    sudo pacman -S --needed nvidia nvidia-lts lib32-nvidia-utils

    # WINE stuff
    sudo pacman -S --needed wine-staging wine_gecko wine-mono lutris

    # Battle.net dependencies
    sudo pacman -S --needed lib32-gnutls lib32-libldap lib32-libgpg-error lib32-sqlite lib32-libpulse 

    # More 32 bit libraries
    sudo pacman -S --needed lib32-alsa-plugins lib32-vulkan-icd-loader
    print_done
  else
    exit_script_on_failure "You must enable the multilib repositories in /etc/pacman.conf to install gaming software."
  fi
elif grep -q laptop /etc/hostname; then
  # Power management
  sudo pacman -S --needed smartmontools tlp x86_energy_perf_policy

  # Wayland packages 
  sudo pacman -S bemenu grim light mako sway swaylock wl-clipboard

  if [ -x "$(command -v "yay")" ]; then
    yay -S redshift-wlr-gamma-control waybar
  fi
fi
print_done

# Print summary info for user
printf "[%s✔%s] Bash script %s complete.\n" "${GREEN}" "${NC}" "${SCRIPT_NAME}"
