#!/bin/bash
#
# Description: Sets up Fedora Linux with the software I use, and 
#              configures various aspects of the system to my liking.
#
# Homepage: https://gitlab.com/krathalan
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# sed usage from https://bbs.archlinux.org/viewtopic.php?id=173653

# ------------------
# --- Guidelines ---
# ------------------

# This script follows the Google Shell Style Guide: 
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# -----------------------------
# ----- Program variables -----
# -----------------------------

readonly USER_HOME=$(eval echo ~"${SUDO_USER}")

installGamingSoftware=false

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

#######################################
# Prints "Done."
# Globals:
#   none
# Arguments:
#   none
# Returns:
#   none
#######################################
print_done() {
  echo -e "Done.\n"
}

# --------------------------------------
# --------------- Script ---------------
# --------------------------------------

# Parse flags. From:
# https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash/7069755#7069755
while test $# -gt 0; do
  case "$1" in
    -g)
      installGamingSoftware=true;
      break
      ;;
    *)
      break
      ;;
  esac
done

# Print intro
readonly scriptName=$(basename "$0")
echo -e "Starting ${scriptName} BASH script; Copyright (C) 2019 krathalan"
echo -e "This is free software: you are free to change and redistribute it."
echo -e "There is NO WARRANTY, to the extent permitted by law.\n"

echo -e "This script should NOT be run as root (or sudo)!"
read -r -p "Press enter when you are ready to continue, or <CTRL+C> to exit: "

echo -e "Disabling Fedora Modular repos..."
sudo sed -i "s#enabled=1#enabled=0#g" /etc/yum.repos.d/fedora-modular.repo
sudo sed -i "s#enabled=1#enabled=0#g" /etc/yum.repos.d/fedora-updates-modular.repo
print_done

echo -e "Removing unused software..."
sudo dnf remove -y cheese gedit gnome-boxes gnome-documents \
gnome-getting-started-docs gnome-initial-setup gnome-maps gnome-photos \
gnome-shell-extension-alternate-tab gnome-shell-extension-apps-menu \
gnome-shell-extension-background-logo gnome-shell-extension-launch-new-instance \
gnome-shell-extension-places-menu gnome-shell-extension-window-list \
gnome-software gnome-user-docs gnome-weather rhythmbox simple-scan totem \
totem-plugins yelp
print_done

echo -e "Removing ABRT..."
sudo dnf remove -y abrt*
print_done

echo -e "Installing packages from RPM..."
sudo dnf install -y android-tools borgbackup easytag epiphany evince ffmpeg firefox \
firejail flatpak gimp git glmark2 gnome-calculator gnome-calendar gnome-clocks \
gnome-menus gnome-mpv gnome-tweaks google-roboto-fonts google-roboto-mono-fonts \
gthumb jq keepassxc kleopatra libreoffice linux-libertine-fonts lm_sensors lz4 \
mediawriter mosh nano neofetch perl-Image-ExifTool pv python3-streamlink \
qbittorrent seahorse ShellCheck stress syncthing tilix youtube-dl Zim zstd
print_done

echo -e "Installing Flatpaks from Flathub..."
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub com.discordapp.Discord
flatpak install -y flathub org.freac.freac
flatpak install -y flathub org.gtk.Gtk3theme.Materia-dark
flatpak install -y flathub org.signal.Signal
flatpak install -y flathub org.gnome.Lollypop
flatpak install -y flathub org.gnome.Fractal
flatpak update -y # Needed to force flatpak to install drivers and themes
print_done

# From https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo#how-to-install-for-other-distros
echo -e "Installing VSCodium..."
sudo rpm --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
sudo dnf config-manager --add-repo https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/rpms/
sudo dnf update
# Enable gpgcheck for this repo
sudo /bin/sh -c 'echo -e "\ngpgcheck=1" >> /etc/yum.repos.d/gitlab.com_paulcarroty_vscodium-deb-rpm-repo_raw_repos_rpms_.repo'
sudo dnf install -y vscodium
print_done

# From https://github.com/nana-4/materia-theme#installation
# https://copr.fedorainfracloud.org/coprs/tcg/themes/
echo -e "Installing Materia theme..."
sudo dnf copr enable -y tcg/themes
sudo dnf install -y materia-theme
print_done

# From https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#papirus-installer
echo -e "Installing Papirus icons..."
sudo dnf copr enable -y dirkdavidis/papirus-icon-theme
sudo dnf install -y papirus-icon-theme
print_done

# From https://copr.fedorainfracloud.org/coprs/dirkdavidis/papirus-libreoffice-theme/
# The package is misnamed in the "Installation Instructions". If you open the Packages
# tab, the only package available is libreoffice-style-papirus
echo -e "Installing Papirus LibreOffice theme..."
sudo dnf copr enable -y dirkdavidis/papirus-libreoffice-theme
sudo dnf install -y libreoffice-style-papirus
print_done

# From https://www.wireguard.com/install/
echo -e "Installing Wireguard..."
sudo dnf copr enable -y jdoss/wireguard
sudo dnf install -y wireguard-dkms wireguard-tools
print_done

if [ "$installGamingSoftware" = true ]; then
  echo -e "Setting up Lutris gaming environment..."
  sudo dnf install -y lutris

  # Install Battle.net dependencies https://github.com/lutris/lutris/wiki/Game:-Blizzard-App
  sudo dnf install -y gnutls gnutls-devel openldap openldap-devel libgpg-error sqlite2.i686 sqlite2.x86_64 
  print_done

  echo -e "Installing WINE..."
  sudo dnf install -y wine
  print_done
fi

# From https://bbs.archlinux.org/viewtopic.php?id=173653
echo -e "Adding .gif thumbnails to GNOME Files (Nautilus)..."
sudo dnf install -y ffmpegthumbnailer
sudo sed -i "s#MimeType=#MimeType=image/gif;#" /usr/share/thumbnailers/ffmpegthumbnailer.thumbnailer
rm -rf "$USER_HOME/.cache/thumbnails"
print_done

# Make sudo show password typing feedback with asterisks
echo -e "Setting up pwfeedback in /etc/sudoers..."
sudo sed -i "s#env_reset#env_reset, pwfeedback#" /etc/sudoers
print_done

# Make Firefox use Wayland if the user is running Wayland
displayServer=$(env | grep -i XDG_SESSION_TYPE)
if [[ "${displayServer}" == *"wayland" ]]; then
  sudo /bin/sh -c 'echo -e "\nMOZ_ENABLE_WAYLAND=1" >> /etc/environment'
fi

echo -e "Making Qt apps look like your GTK+ theme..."
sudo dnf install -y qt5-qtstyleplugins
sudo /bin/sh -c 'echo -e "\nQT_QPA_PLATFORMTHEME=gtk2" >> /etc/environment'
print_done

echo -e "Reboot your computer now!"
