#!/usr/bin/env sh
#
# Description: Checks all sh and bash scripts in the current directory
#              with shellcheck.
#
# Homepage: https://github.com/krathalan/miscellaneous-scripts
#
# Copyright (C) 2019-2024 Hunter Peavey
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -----------------------------------------
# -------------- Guidelines ---------------
# -----------------------------------------

# This script follows the Google Shell Style Guide:
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eu # (Eo pipefail) is Bash only!

# -----------------------------------------
# ----------- Program variables -----------
# -----------------------------------------

# Colors
RED=$(tput bold && tput setaf 1)
GREEN=$(tput bold && tput setaf 2)
WHITE=$(tput sgr0 && tput bold)
NC=$(tput sgr0) # No color/turn off all tput attributes
readonly RED GREEN WHITE NC

# Step variables
stepCounter=1

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

#######################################
# Prints passed error message before premature exit.
# Prints everything to >&2 (STDERR).
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: error message to print
# Returns:
#   none
#######################################
exit_script_on_failure()
{
  printf "%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
  exit 1
}

#######################################
# Properly formats a step statement.
# Globals:
#   stepCounter, GREEN, NC, WHITE
# Arguments:
#   none
# Returns:
#   none
#######################################
print_step()
{
  printf "%s==> %s%s. %s%s" "${GREEN}" "${WHITE}" "${stepCounter}" "$1" "${NC}"
}

# -----------------------------------------
# ---------------- Script -----------------
# -----------------------------------------

[ "$(whoami)" = "root" ] &&
  exit_script_on_failure "This script should NOT be run as root (or sudo)!"

printf "Checking scripts in working directory...\n\n"

# Get the file name without the full path
fileName=""

for file in ./*; do
  if [ ! -d "${file}" ] && head -n1 "${file}" | grep -q "#!/.*sh"; then
    fileName="$(realpath --relative-to=. "${file}")"
    print_step "${fileName}"

    # Don't fail out of script if shellcheck "fails" due to errors
    # in checked file
    shellcheck "${file}" || :

    printf "\n\n"
    stepCounter=$(( stepCounter + 1 ))
  fi
done

printf "Done.\n"
