#!/bin/bash
#
# Description: Sets up Fedora Linux with the software I use, and 
#              configures various aspects of the system to my liking.
#
# Homepage: https://gitlab.com/krathalan
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# sed usage from https://bbs.archlinux.org/viewtopic.php?id=173653

# ------------------
# --- Guidelines ---
# ------------------

# This script follows the Google Shell Style Guide: 
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

#######################################
# Gets the current branch a git repository is on.
# Globals:
#   none
# Arguments:
#   none
# Returns:
#   current branch of git repository
#######################################
get_current_branch()
{
  local branch
  branch=$(git status | grep -i "on branch" | awk '{printf $3}')

  # Return 
  echo "$branch"
}

# --------------------------------------
# --------------- Script ---------------
# --------------------------------------

# Print intro
readonly scriptName=$(basename "$0")
echo -e "Starting $scriptName BASH script; Copyright (C) 2019 krathalan"
echo -e "This is free software: you are free to change and redistribute it."
echo -e "There is NO WARRANTY, to the extent permitted by law.\n"

echo -e "This script should NOT be run as root (or sudo)!\n"

echo -e "Updating git repos..."

readonly baseDir="/home/anders/GitLab"
currentBranch=""

for dir in "$baseDir"/*; do
  (
  cd "$dir" || exit
  currentBranch=$(get_current_branch)
  git pull origin "$currentBranch" 
  echo ""
  )
done

echo -e "Done."