#!/bin/bash
#
# Description: Updates DXVK in /opt.
#
# Homepage: https://gitlab.com/krathalan
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -----------------------------
# ----- Program variables -----
# -----------------------------

releaseNumber="$1"

# --------------------------------------
# --------------- Script ---------------
# --------------------------------------

echo -e "This script should be run AS ROOT (or sudo)!"
read -r -p "Press enter when you are ready to continue, or <CTRL+C> to exit: "
echo -e ""

(
cd /opt || exit
rm -rf dxvk*
wget "https://github.com/doitsujin/dxvk/releases/download/v${releaseNumber}/dxvk-${releaseNumber}.tar.gz" --directory-prefix="/opt" -q --show-progress
tar -xf "dxvk-${releaseNumber}".tar.gz
rm -f "dxvk-${releaseNumber}".tar.gz
)

echo -e "Done."