#!/bin/bash
#
# Description: Updates DXVK in ~/.local/bin.
#
# Homepage: https://gitlab.com/krathalan
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -----------------------------
# ----- Program variables -----
# -----------------------------

# Colors
readonly RED=$(tput bold && tput setaf 1)
readonly NC=$(tput sgr0) # No color/turn off all tput attributes

readonly DXVK_FILE_PATH="${HOME}/.local/bin"
readonly RELEASE_NUMBER="$1"
readonly SCRIPT_NAME=$(basename "$0")

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

#######################################
# Prints passed error message before premature exit.
# Prints everything to >&2 (STDERR).
# Globals:
#   RED, NC
#   SCRIPT_NAME
# Arguments:
#   $1: error message to print
# Returns:
#   none
#######################################
exit_script_on_failure() {
  printf "%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
  printf "Exiting %s Bash script.\n" "${SCRIPT_NAME}" >&2

  exit 1
}

# --------------------------------------
# --------------- Script ---------------
# --------------------------------------

# Print intro
echo -e "Starting ${SCRIPT_NAME} Bash script; Copyright (C) 2019 krathalan"
echo -e "This is free software: you are free to change and redistribute it."
echo -e "There is NO WARRANTY, to the extent permitted by law.\n"

if [[ $(whoami) == "root" ]]; then
  exit_script_on_failure "This script should NOT be run as root (or sudo)!"
fi

(
  mkdir -p "${DXVK_FILE_PATH}"
  cd "${DXVK_FILE_PATH}" || exit
  rm -rf dxvk*
  wget "https://github.com/doitsujin/dxvk/releases/download/v${RELEASE_NUMBER}/dxvk-${RELEASE_NUMBER}.tar.gz" --directory-prefix="${DXVK_FILE_PATH}" -q --show-progress
  tar -xf "dxvk-${RELEASE_NUMBER}".tar.gz
  rm -f "dxvk-${RELEASE_NUMBER}".tar.gz
)

echo -e "\nDone."