#!/bin/bash
#
# Description: Updates git repos in the user's ~/GitLab directory.
#
# Homepage: https://gitlab.com/krathalan
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# sed usage from https://bbs.archlinux.org/viewtopic.php?id=173653

# ------------------
# --- Guidelines ---
# ------------------

# This script follows the Google Shell Style Guide: 
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# -----------------------------------------
# ----------- Program variables -----------
# -----------------------------------------

readonly BASE_DIR="${HOME}/GitLab"
readonly SCRIPT_NAME=$(basename "$0")

# --------------------------------------
# --------------- Script ---------------
# --------------------------------------

# Print intro
echo -e "Starting ${SCRIPT_NAME} Bash script; Copyright (C) 2019 krathalan"
echo -e "This is free software: you are free to change and redistribute it."
echo -e "There is NO WARRANTY, to the extent permitted by law.\n"

echo -e "Updating git repos..."

for dir in "${BASE_DIR}"/*; do
  (
  cd "${dir}" || exit
  git pull origin "$(git status | grep "On branch" | awk '{printf $3}')" 
  echo ""
  )
done

echo -e "Done."