#!/bin/bash
#
# Description: Updates DXVK in /opt.
#
# Homepage: https://gitlab.com/krathalan
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -----------------------------
# ----- Program variables -----
# -----------------------------

readonly DXVK_FILE_PATH="${HOME}/.local/bin"
readonly RELEASE_NUMBER="$1"

# --------------------------------------
# --------------- Script ---------------
# --------------------------------------

# Print intro
readonly scriptName=$(basename "$0")
echo -e "Starting ${scriptName} BASH script; Copyright (C) 2019 krathalan"
echo -e "This is free software: you are free to change and redistribute it."
echo -e "There is NO WARRANTY, to the extent permitted by law.\n"

echo -e "This script should not be run as root (or sudo)!"
echo -e ""

(
  mkdir -p "${DXVK_FILE_PATH}"
  cd "${DXVK_FILE_PATH}" || exit
  rm -rf dxvk*
  wget "https://github.com/doitsujin/dxvk/releases/download/v${RELEASE_NUMBER}/dxvk-${RELEASE_NUMBER}.tar.gz" --directory-prefix="${DXVK_FILE_PATH}" -q --show-progress
  tar -xf "dxvk-${RELEASE_NUMBER}".tar.gz
  rm -f "dxvk-${RELEASE_NUMBER}".tar.gz
)

echo -e "\nDone."